### GENERAL SETTINGS ###
#

gems: [jekyll-timeago]

# Site settings
title: Inspire Athens
description: "Lets get together, be creative, and initiate collaborative activities to inspire each other. Promoting events and organizing gatherings with discussions, workshops, missions and jam sessions."
author: "Raphael Varonos"
analytics: "UA-59822601-1"
baseurl: "" #important: start with /
url: "http://inspireathens.github.io"
url_s: "https://inspireathens.github.io"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

exclude: [README.md,Gemfile]

features:
- title: Host
  event: Cafeterias, Bars, Restaurants, etc
  gathering: Me and the Participants
- title: Entrance (free)
  event: Public
  gathering: Public or by Invitation  
- title: Activities
  event: Few 
  gathering: Many
- title: Food and Drinks
  event: Limited
  gathering: Free and Plenty
- title: Equipment
  event: Unknown
  gathering: Listed